import { ForgeUpgradeDefinition } from '../types/forge';
import { LIFETIME_EP_STORAGE_KEY } from './explorationConfig';

export const FORGE_UPGRADES_STORAGE_KEY = 'animatrix_forge_upgrades_v3';
export { LIFETIME_EP_STORAGE_KEY };

export const FORGE_UPGRADES_CONFIG: ForgeUpgradeDefinition[] = [
  {
    id: 'alloy_armor',
    name: 'HEALTH',
    category: 'HEALTH',
    statLabel: 'HEALTH',
    tagline: '+100 HP per star',
    description: 'Increases your robot\'s maximum health (+100 HP per star).',
    icon: '❤️',
    maxLevel: 10,
    costCurve: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
    benefitPerLevelPercent: 10,
    progressionLabels: [
      'Base Health',
      '+100 HP (1 star)',
      '+200 HP (2 stars)',
      '+300 HP (3 stars)',
      '+400 HP (4 stars)',
      '+500 HP (5 stars)',
      '+600 HP (6 stars)',
      '+700 HP (7 stars)',
      '+800 HP (8 stars)',
      '+900 HP (9 stars)',
      '+1000 HP (MAX)',
    ],
  },
  {
    id: 'energon_overdrive',
    name: 'FIRE RATE',
    category: 'FIRE_RATE',
    statLabel: 'FIRE RATE',
    tagline: '+1.0/s fire rate per star',
    description: 'Decreases reload delay so your robot shoots faster (+1.0/s per star).',
    icon: '🔥',
    maxLevel: 10,
    costCurve: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
    benefitPerLevelPercent: 12.5,
    progressionLabels: [
      'Base Fire Rate',
      '+1.0/s Fire Rate (1 star)',
      '+2.0/s Fire Rate (2 stars)',
      '+3.0/s Fire Rate (3 stars)',
      '+4.0/s Fire Rate (4 stars)',
      '+5.0/s Fire Rate (5 stars)',
      '+6.0/s Fire Rate (6 stars)',
      '+7.0/s Fire Rate (7 stars)',
      '+8.0/s Fire Rate (8 stars)',
      '+9.0/s Fire Rate (9 stars)',
      '+10.0/s Fire Rate (MAX)',
    ],
  },
  {
    id: 'special_core',
    name: 'SPECIAL',
    category: 'SPECIAL',
    statLabel: 'SPECIAL',
    tagline: '+10 special damage per star',
    description: 'Powers up your robot\'s special skill (+10 Special per star).',
    icon: '✨',
    maxLevel: 10,
    costCurve: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
    benefitPerLevelPercent: 5,
    progressionLabels: [
      'Base Special',
      '+10 Special (1 star)',
      '+20 Special (2 stars)',
      '+30 Special (3 stars)',
      '+40 Special (4 stars)',
      '+50 Special (5 stars)',
      '+60 Special (6 stars)',
      '+70 Special (7 stars)',
      '+80 Special (8 stars)',
      '+90 Special (9 stars)',
      '+100 Special (MAX)',
    ],
  },
  {
    id: 'impact_amplifier',
    name: 'DAMAGE',
    category: 'DAMAGE',
    statLabel: 'DAMAGE',
    tagline: '+20 damage per star',
    description: 'Increases the damage dealt by your attacks in battle (+20 Damage per star).',
    icon: '⚔️',
    maxLevel: 10,
    costCurve: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
    benefitPerLevelPercent: 15,
    progressionLabels: [
      'Base Damage',
      '+20 Damage (1 star)',
      '+40 Damage (2 stars)',
      '+60 Damage (3 stars)',
      '+80 Damage (4 stars)',
      '+100 Damage (5 stars)',
      '+120 Damage (6 stars)',
      '+140 Damage (7 stars)',
      '+160 Damage (8 stars)',
      '+180 Damage (9 stars)',
      '+200 Damage (MAX)',
    ],
  },
];
